# Generated by Django 2.0.6 on 2018-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipName', models.CharField(max_length=20, verbose_name='会员名')),
                ('vipPwd', models.CharField(max_length=20, verbose_name='会员密码')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'vip',
            },
        ),
    ]
